name = "Furrave Livesets"
license = "MIT"
licenselink = "https://github.com/zowie/furrave/blob/master/LICENSE.md"
description = "Theme for the Furrave Livesets website"
homepage = "https://zowie.im/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Zowie the Lynx"
  homepage = "https://zowie.im"
